name: ci-pipeline
on:
    push:
        branches: 
            - '**'    
jobs:
    Linting:
        runs-on: ubuntu-latest
        steps:
            - name: First Step
              run: echo "Allah Please Help Me"
            - name: Checkout GitHub Repo
              uses: actions/checkout@v4
            - name: Checkout Confirmation
              run: echo "GitHUB Repo= ${{github.repository}}" "Runner Workspace ${{github.workspace}}"